[Experiment] If the 'target page' frame does not have an ID to match
We get 'content missing' and the content wrapped in the frame in the
source page disappears.

We get the following error in the console:

Error: The response (200) did not contain the expected
 <turbo-frame id="first turbo frame"> and will be ignored.
 To perform a full page visit instead, set turbo-visit-control to reload.